### PR TITLE
fix popovers and tooltips scrolling issue

### PR DESCRIPTION
**Pull request by aaminev**

### CODE REVIEW

**Comment by MiguelMadero** [comment]
LGTM

**Comment by MiguelMadero** [comment]
LGTM

**Comment by aaminev** [comment]
@MiguelMadero I've rebased from `zenefits-beta`. looks like 1 test if failing...

**Comment by MiguelMadero** [comment]
Can you edit .travis.yml and move ember-canary to the allowed failures list ?

**Comment by MiguelMadero** [comment]
It passed after a retry... this is odd, seems like a flaky test :( but that's unrelated to your changes.

**Comment by MiguelMadero** [comment]
Can you cut a new beta release and update ?

**Pull request merged**
